### ISSUE TITLE
Failed compilation with python3

### ISSUE THREAD

**Issue by epagone** [szaghi/FoBiS#111]
I connot compile on my Ubuntu 18.04 machine:
```
$ FoBiS.py build
Traceback (most recent call last):
  File "/usr/local/bin/FoBiS.py", line 21, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/fobis/fobis.py", line 45, in main
    run_fobis()
  File "/usr/local/lib/python3.6/dist-packages/fobis/fobis.py", line 58, in run_fobis
    configuration = FoBiSConfig(fake_args=fake_args)
  File "/usr/local/lib/python3.6/dist-packages/fobis/FoBiSConfig.py", line 65, in __init__
    self.fobos = Fobos(cliargs=self.cliargs, print_n=self.print_b, print_w=self.print_r)
  File "/usr/local/lib/python3.6/dist-packages/fobis/Fobos.py", line 76, in __init__
    self._set_cliargs(cliargs=cliargs)
  File "/usr/local/lib/python3.6/dist-packages/fobis/Fobos.py", line 238, in _set_cliargs
    self._check_local_variables()
  File "/usr/local/lib/python3.6/dist-packages/fobis/Fobos.py", line 176, in _check_local_variables
    self._get_local_variables()
  File "/usr/local/lib/python3.6/dist-packages/fobis/Fobos.py", line 144, in _get_local_variables
    for item in self.fobos.items(section):
  File "/usr/lib/python3.6/configparser.py", line 858, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.6/configparser.py", line 858, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.6/configparser.py", line 855, in <lambda>
    section, option, d[option], d)
  File "/usr/lib/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%^%StringiFor/%" -czf StringiFor.tar.gz *'
```
(as you can see I was trying to compile StringiFor).

```
$ FoBiS.py --version
FoBiS.py 2.9.5

$ python --version
Python 2.7.15+

$ python3 --version
Python 3.6.8
```
I guess the default python on my system is python3.

**Comment by epagone** [comment]
Bug persists (same output) with the new version
```
$ FoBiS.py --version
FoBiS.py 2.9.7

**Comment by epagone** [comment]
I have updated FoBiS
```
$ FoBiS.py --version
FoBiS.py 3.0.0
```
and gave it a go on my machine with python 3.6.9 and `gfortran-9`. It did not go well but maybe I'm doing something wrong.
```
$ FoBiS.py build -compiler custom -fc gfortran-9
The present cflags are different from the heritages one: forcing to (re-)compile all
Builder options
  Directories
    Building directory: "exe"
    Compiled-objects .o   directory: "exe/obj"
    Compiled-objects .mod directory: "exe/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran-9"
    Module directory switch: "-J"
    Compiling flags: "-c -frealloc-lhs -std=f2008 -fall-intrinsics -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building src/tests/stringifor/stringifor-doctest-2.f90
Compiling src/third_party/PENF/src/lib/penf_global_parameters_variables.F90 serially
Compiling src/third_party/PENF/src/lib/penf_b_size.F90 serially
Compiling src/third_party/PENF/src/lib/penf_stringify.F90 serially
Compiling src/third_party/PENF/src/lib/penf.F90 serially
Compiling src/third_party/BeFoR64/src/lib/befor64_pack_data_m.F90 serially
Compiling src/third_party/BeFoR64/src/lib/befor64.F90 serially
Compiling src/lib/stringifor_string_t.F90 serially
src/lib/stringifor_string_t.F90:78:41:

   78 |     generic               :: to_number =>   &
      |                                         1
Error: ‘to_real_r8p’ and ‘to_real_r16p’ for GENERIC ‘to_number’ at (1) are ambiguous
src/lib/stringifor_string_t.F90:103:31:

  103 |     generic :: assignment(=) => string_assign_string,      &
      |                               1
Error: ‘string_assign_real_r8p’ and ‘string_assign_real_r16p’ for GENERIC ‘=’ at (1) are ambiguous
src/lib/stringifor_string_t.F90:2545:14:

 2545 |       form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |              1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:2545:55:

 2545 |       form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                       1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:2514:11:

 2514 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |           1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:2514:52:

 2514 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                    1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1275:10:

 1275 |    join = ''
      |          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1399:22:

 1399 |       partitions(2) = sep_
      |                      1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1400:22:

 1400 |       partitions(3) = ''
      |                      1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1573:11:

 1573 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |           1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1573:52:

 1573 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                    1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1488:17:

 1488 |          form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                 1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1488:58:

 1488 |          form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1334:10:

 1334 |    join = ''
      |          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:990:18:

  990 |       extension = ''
      |                  1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:936:15:

  936 |      encoded = codec
      |               1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:911:15:

  911 |      codec_u = codec
      |               1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)

src/lib/stringifor_string_t.F90:78:41:

   78 |     generic               :: to_number =>   &
      |                                         1
Error: ‘to_real_r8p’ and ‘to_real_r16p’ for GENERIC ‘to_number’ at (1) are ambiguous
src/lib/stringifor_string_t.F90:103:31:

  103 |     generic :: assignment(=) => string_assign_string,      &
      |                               1
Error: ‘string_assign_real_r8p’ and ‘string_assign_real_r16p’ for GENERIC ‘=’ at (1) are ambiguous
src/lib/stringifor_string_t.F90:2545:14:

 2545 |       form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |              1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:2545:55:

 2545 |       form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                       1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:2514:11:

 2514 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |           1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:2514:52:

 2514 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                    1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1275:10:

 1275 |    join = ''
      |          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1399:22:

 1399 |       partitions(2) = sep_
      |                      1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1400:22:

 1400 |       partitions(3) = ''
      |                      1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1573:11:

 1573 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |           1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1573:52:

 1573 |    form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                    1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1488:17:

 1488 |          form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                 1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1488:58:

 1488 |          form_ = 'FORMATTED' ; if (present(form)) form_ = form ; form_ = form_%upper()
      |                                                          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:1334:10:

 1334 |    join = ''
      |          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:990:18:

  990 |       extension = ''
      |                  1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:936:15:

  936 |      encoded = codec
      |               1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
src/lib/stringifor_string_t.F90:911:15:

  911 |      codec_u = codec
      |               1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
```
Running simply `make` using the build-in `makefile` works without any error.

**Comment by szaghi** [comment]
Hi @epagone this is a change due to the new API of StringiFor, not a FoBiS issue: stringifor has not more an "elemental" assignment thus it is not possible to assign an array of strings to a constant literal.

I have to recheck the tests of stringfor, but it is not related to FoBiS: makefile works because probably do not try to compile all the (doc)tests.

**Comment by epagone** [comment]
I did not understand that the errors were related to tests compilation. I thought they were library compilation errors. Thanks for clarifying, @szaghi.

> makefile works because probably do not try to compile all the (doc)tests.

[Yes](https://github.com/szaghi/StringiFor/issues/25).

**Comment by epagone** [comment]
Sorry, @szaghi, but I double checked and it looks like the errors [in this comment](https://github.com/szaghi/FoBiS/issues/111#issuecomment-562717023) are issued building the library, **not** the tests.

**Comment by szaghi** [comment]
@epagone I am not able to replicate your error, the library is correctly compiled in my python 3.8 env and the major part of the tests work, jut the ones relying on previous elemental procedures do not work. Can you minimize your test and let me replicate the error?

**Comment by epagone** [comment]
@szaghi sorry for the basic question, but how can I minimise my test? I was just trying to build the library with FoBiS:
`$ FoBiS.py build -compiler custom -fc gfortran-9`
and with the makefile:
`$ make`.

Can you test compile Stringifor with `HEAD detached at f906e72`? Maybe this is the cause of the error. But still if make is able to build the library without errors, also FoBiS should be able to do so, right? It should not depend on the particular commit of Stringifor.

**Comment by szaghi** [comment]
@epagone 

the current master branch of StringiFor is correctly compiled for me, as well as the most part of the tests. I have not tested the `HEAD detached at f906e72` yet

**Comment by szaghi** [comment]
@epagone 

I have just checked the `f906e72` commit, it seems to work for me:

```bash
┌╼ stefano@zaghi(04:33 PM Mon Dec 09) on f906e72 [?]
├───╼ ~/fortran/StringiFor 17 files, 192Kb
└──────╼ FoBiS.py build -mode tests-gnu -t src/tests/stringifor/stringifor_test_csv_naive_parser.f90 
Module 'pygooglechart' not found: Gcov graphs disabled
Builder options
  Directories
    Building directory: "exe"
    Compiled-objects .o   directory: "exe/obj"
    Compiled-objects .mod directory: "exe/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c -frealloc-lhs -std=f2008 -fall-intrinsics -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building src/tests/stringifor/stringifor_test_csv_naive_parser.f90
Compiling src/third_party/PENF/src/lib/penf_global_parameters_variables.F90 serially
Compiling src/third_party/PENF/src/lib/penf_b_size.F90 serially
Compiling src/third_party/PENF/src/lib/penf_stringify.F90 serially
Compiling src/third_party/PENF/src/lib/penf.F90 serially
Compiling src/third_party/BeFoR64/src/lib/befor64_pack_data_m.F90 serially
Compiling src/third_party/BeFoR64/src/lib/befor64.F90 serially
Compiling src/lib/stringifor_string_t.F90 serially
Compiling src/lib/stringifor.F90 serially
Compiling src/tests/stringifor/stringifor_test_csv_naive_parser.f90 serially
Linking exe/stringifor_test_csv_naive_parser
Target src/tests/stringifor/stringifor_test_csv_naive_parser.f90 has been successfully built
```

I have also tested with

```bash
┌╼ stefano@zaghi(04:52 PM Mon Dec 09) on f906e72 [?]
├───╼ ~/fortran/StringiFor 18 files, 216Kb
└──────╼ FoBiS.py build -compiler custom -fc gfortran
,,,
Building src/tests/stringifor/stringifor-doctest-1.f90
Compiling src/tests/stringifor/stringifor-doctest-1.f90 serially
Linking exe/stringifor-doctest-1
Target src/tests/stringifor/stringifor-doctest-1.f90 has been successfully built
Builder options
  Directories
    Building directory: "exe"
    Compiled-objects .o   directory: "exe/obj"
    Compiled-objects .mod directory: "exe/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c -frealloc-lhs -std=f2008 -fall-intrinsics -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []
```
and all seems good, all tests are correctly compiled and obviously also the library.

**Comment by epagone** [comment]
Hi @szaghi, after a lot of fiddling I'm still scratching my head. I realised that somehow I had `BeFoR64` and `PENF` out of sync while I was in `f906e72`: `git status` was reporting unstaged changes for both the dependencies (I don't know why). I tried to rectify the situation in many ways with no luck and finally I decided to delete the entire local repository and started from scratch. After re-cloning and `git submodule update --init`, I finally got
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```
Still, I cannot complete build StringiFor with FoBiS. This is the output:
```
$ FoBiS.py build -compiler custom -fc gfortran-9
Builder options
  Directories
    Building directory: "exe"
    Compiled-objects .o   directory: "exe/obj"
    Compiled-objects .mod directory: "exe/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran-9"
    Module directory switch: "-J"
    Compiling flags: "-c -frealloc-lhs -std=f2008 -fall-intrinsics -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building src/tests/stringifor/stringifor-doctest-2.f90
Compiling src/third_party/PENF/src/lib/penf_global_parameters_variables.F90 serially
Compiling src/third_party/PENF/src/lib/penf_b_size.F90 serially
Compiling src/third_party/PENF/src/lib/penf_stringify.F90 serially
Compiling src/third_party/PENF/src/lib/penf.F90 serially
Compiling src/third_party/BeFoR64/src/lib/befor64_pack_data_m.F90 serially
Compiling src/third_party/BeFoR64/src/lib/befor64.F90 serially
Compiling src/lib/stringifor_string_t.F90 serially
Compiling src/lib/stringifor.F90 serially
Compiling src/tests/stringifor/stringifor-doctest-2.f90 serially
Linking exe/stringifor-doctest-2
Target src/tests/stringifor/stringifor-doctest-2.f90 has been successfully built
Builder options
  Directories
    Building directory: "exe"
    Compiled-objects .o   directory: "exe/obj"
    Compiled-objects .mod directory: "exe/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran-9"
    Module directory switch: "-J"
    Compiling flags: "-c -frealloc-lhs -std=f2008 -fall-intrinsics -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building src/tests/stringifor/stringifor_test_parse_large_csv.f90
Compiling src/tests/stringifor/stringifor_test_parse_large_csv.f90 serially
src/tests/stringifor/stringifor_test_parse_large_csv.f90:33:10:

   33 | columns = '----' ! re-use columns for printing separators
      |          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)

src/tests/stringifor/stringifor_test_parse_large_csv.f90:33:10:

   33 | columns = '----' ! re-use columns for printing separators
      |          1
Error: Cannot convert CHARACTER(1) to TYPE(string) at (1)
```
But if I do
```
$ FoBiS.py clean
Removing all *.(s)mod files into "exe/mod"
Removing all *.o files into "exe/obj"
$ make
Compile penf_global_parameters_variables.F90
Compile penf_b_size.F90
Compile penf_stringify.F90
Compile penf.F90
Compile befor64_pack_data_m.F90
Compile befor64.F90
Compile stringifor_string_t.F90
Compile stringifor.F90
Assemble STRINGIFOR
```
all works well. I don't understand where I'm wrong.

**Comment by szaghi** [comment]
@epagone 

As I said, the test `stringifor_test_parse_large_csv.f90` (and many others) does not work in the new StringiFor library: I have changed the assignment operator that is now pure, but not elemental thus the instruction `columns = '----'` is no more possible because `columns` is an array while `'----'` is a scalar constant literal. This is not a problem of FoBiS rather a problem of mine that I have not yet updated all the tests of StringiFor.

**Comment by epagone** [comment]
@szaghi Apologies: you're right. Many many thanks for fixing this bug!

**Comment by szaghi** [comment]
@epagone you are welcome, thank you for your feedback it is really appreciated
