### ISSUE TITLE
Coverage crash

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#124]
I'm seeing a crash like this with gfortran 9 in GitHub actions, using coverage:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.13/x64/bin/FoBiS.py", line 29, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fobis/fobis.py", line 51, in main
    run_fobis()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fobis/fobis.py", line 66, in run_fobis
    run_fobis_rule(configuration)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fobis/fobis.py", line 158, in run_fobis_rule
    gcov_analyzer(configuration=configuration)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fobis/fobis.py", line 555, in gcov_analyzer
    gcov.parse()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fobis/Gcov.py", line 225, in parse
    ignoring = _coverage_update(ignoring=ignoring, cov_num=cov_num, line_num=line_num, text=text, coverage=self.coverage)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fobis/Gcov.py", line 201, in _coverage_update
    coverage.append(int(cov_num))
ValueError: invalid literal for int() with base 10: '50756163*'
```

It doesn't appear to be accounting for these lines with '*' in them. Is that something new in gcov (I think I was using gcov-6 before).

**Comment by szaghi** [comment]
@jacobwilliams 

It has been a while since I used gcov (I am developing a new huge code that is not ready for coverage assessment) thus I am not sure that is something related to new versions of gcov. 

I will try to dig this deeper asap.

Cheers

**Comment by jacobwilliams** [comment]
I think it may have been a change in gcc 8.

**Comment by jacobwilliams** [comment]
This was fixed in #132.
