### ISSUE TITLE
Another Python3 Issue

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#34]
If the source file has a syntax error, then I'm getting an error when running FoBiS with Python 3.4.2.

```python
Traceback (most recent call last):
  File "/Users/anaconda/bin/FoBiS.py", line 5, in <module>
    main()
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/fobis.py", line 140, in main
    build()
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/fobis.py", line 90, in build
    builder.build(file_to_build=pfile, output=__config__.cliargs.output, nomodlibs=nomodlibs)
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/Builder.py", line 302, in build
    print(self.colors.red + result[1] + self.colors.end)
TypeError: Can't convert 'bytes' object to str implicitly
```

This can be seen when trying to compile the following file (src/test.f90):

```fortran
program blah

abc

end program blah
```
with the command:

```bash
FoBiS.py build -s ./src -compiler gnu
```

**Comment by szaghi** [comment]
Thank you Jacob. I do not test deep with python 3.x. Tomorrow I will try fix this bug and I will add a test unit for compiling bugged sources like your.

See you soon.

**Comment by szaghi** [comment]
The new release 1.3.2 on both PyPi and github should be free of this bug.

See you soon.
