### ISSUE TITLE
Adding to homebrew, but found a bug

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#76]
Hi Stefano,
I'm trying to add FoBiS.py to Homebrew. However, I found what appears to be a bug:

```bash
FoBiS.py build -compiler Custom -fc gfortran
Traceback (most recent call last):
  File "/usr/local/bin/FoBiS.py", line 21, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/fobis/fobis.py", line 30, in main
    __config__.run_fobis()
  File "/usr/local/lib/python2.7/site-packages/fobis/config.py", line 663, in run_fobis
    self._build()
  File "/usr/local/lib/python2.7/site-packages/fobis/config.py", line 543, in _build
    builder = Builder(cliargs=self.cliargs, print_n=self._print_b, print_w=self._print_r)
  File "/usr/local/lib/python2.7/site-packages/fobis/Builder.py", line 102, in __init__
    self.compiler = Compiler(cliargs=cliargs, print_w=self.print_w)
  File "/usr/local/lib/python2.7/site-packages/fobis/Compiler.py", line 108, in __init__
    self._set_cflags()
  File "/usr/local/lib/python2.7/site-packages/fobis/Compiler.py", line 177, in _set_cflags
    if self.preproc is not None:
AttributeError: 'Compiler' object has no attribute 'preproc'
```

But the source files build with gfortran, without problem and require no preprocessing.

**Comment by zbeekman** [comment]
hmmm I guess many of the flags are non-optional when using "custom" compiler. I wonder if a better error message would be possible in this case, and improved documentation.

**Comment by szaghi** [comment]
Yes, you are right, with custom compiler some other flagsare not opyional. I am very sorry, but I am on my holidays and I cannot do nothing gor improving the errors trapping. I will try next days if my family look on the other side...

**Comment by zbeekman** [comment]
no worries, enjoy your holiday! I can actually just add the documentation myself in the wiki!

**Comment by zbeekman** [comment]
Added to Homebrew!

I'm going to close it, since it's not really a bug. I'll try to update the wiki next week.

**Comment by szaghi** [comment]
Thank you very much Zaak!
