### ISSUE TITLE
Python3.4.4 crash

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#83]
FoBiS is crashing for me when compiling `json-fortran` (and other projects) with Python 3.4.4. See below. It works fine with Python 2.7.

```bash
$ python --version
Python 3.4.4 :: Anaconda 2.0.1 (x86_64)

$ gfortran --version
GNU Fortran (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

$ ./build.sh 

Building library...
Traceback (most recent call last):
  File "/Users/anaconda/bin/FoBiS.py", line 21, in <module>
    main()
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/fobis.py", line 39, in main
    run_fobis()
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/fobis.py", line 62, in run_fobis
    run_fobis_build(configuration)
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/fobis.py", line 77, in run_fobis_build
    pfiles = parse_files(configuration=configuration)
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/fobis.py", line 202, in parse_files
    pfile.parse(inc=configuration.cliargs.inc)
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/ParsedFile.py", line 298, in parse
    self.doctest.parse(source=file(self.name, 'r').read())
NameError: name 'file' is not defined
```

**Comment by szaghi** [comment]
Hi Jacob,
The support for Python 3.x is somehow *fragile*, just because I still prefer 2.7.x. 

Tomorrow I will try to fix this bug.

Stay tuned :smile:

**Comment by szaghi** [comment]
Hi Jacob,

in the new 1.9.2 (present both in the master branch here and on PyPi) I have fixed this small Python 3.x incompatibility. 

I have not Python 3.4.x, but only 3.5. In my test `json-fortran` tests are built:

```shell
→ ./build.sh 

Building library...
Builder options
  Directories
    Building directory: "lib"
    Compiled-objects .o   directory: "lib"
    Compiled-objects .mod directory: "lib"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c -O2 -fbacktrace -Wall -Wextra -Wno-maybe-uninitialized -Wno-unused-function -pedantic -std=f2008 -fno-omit-frame-pointer"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building src/json_module.F90
Nothing to compile, all objects are up-to-date
Linking lib/libjsonfortran.a
Target src/json_module.F90 has been successfully built

Building unit tests...
Build jf_test_10
...
```

Let me know if this fix is correct for you.

I will improve the 3.x support soon.

Thank you for your help.

**Comment by szaghi** [comment]
@jacobwilliams Hi Jacob, can you give me a feedback? Has this patch solved the bug?

See you soon.
