### ISSUE TITLE
UnicodeDecodeError on Python 3

### ISSUE THREAD

**Issue by Juanlu001** [szaghi/FoBiS#84]
I just tried to build https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit/blob/master/build.sh but got this error on Python 3.5:

```
Building tests/dro/dro_test.f90
Compiling tests/dro/dro_test.f90 serially
Traceback (most recent call last):
  File "/home/juanlu/.miniconda3/envs/poliastro35/bin/FoBiS.py", line 21, in <module>
    main()
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/fobis/fobis.py", line 39, in main
    run_fobis()
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/fobis/fobis.py", line 62, in run_fobis
    run_fobis_build(configuration)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/fobis/fobis.py", line 94, in run_fobis_build
    build_pfile(configuration=configuration, pfile=pfile, pfiles=pfiles, nomodlibs=nomodlibs, builder=builder)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/fobis/fobis.py", line 249, in build_pfile
    builder.build(file_to_build=pfile, output=configuration.cliargs.output, nomodlibs=nomodlibs, mklib=configuration.cliargs.mklib, verbose=configuration.cliargs.verbose, log=configuration.cliargs.log)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/fobis/Builder.py", line 556, in build
    build_ok = self._compile(file_to_build=file_to_build, verbose=verbose, log=log, quiet=quiet)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/fobis/Builder.py", line 478, in _compile
    result = syswork(cmd)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/fobis/utils.py", line 42, in syswork
    output = output.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 99: ordinal not in range(128)
```

This problem does not exist on Python 2.

**Comment by szaghi** [comment]
Hi @Juanlu001 

This should be a quite simple bug. The support for python 3.x is quite *fragile* presently, I am sorry. Tomorrow I will try to fix it, stay tuned.

See you tomorrow.

**Comment by szaghi** [comment]
@Juanlu001 in the new version v1.9.3 (both on the master branch here and on PyPi) this issue should be fixed. 

```shell
→ ./build.sh
...
Building src/fortran_astrodynamics_toolkit.f90
Nothing to compile, all objects are up-to-date
Linking lib/libfat.a
Target src/fortran_astrodynamics_toolkit.f90 has been successfully built
build test programs
Attention: the file 'tests/cw_test/cw_test.f90' depends on 'pyplot_module' that is unreachable
Attention: the file 'tests/crtbp/crtbp_test.f90' depends on 'pyplot_module' that is unreachable
Attention: the file 'tests/dro/dro_test.f90' depends on 'pyplot_module' that is unreachable
Builder options
  Directories
    Building directory: "bin"
    Compiled-objects .o   directory: "bin"
    Compiled-objects .mod directory: "bin"
  Included paths: lib 
  Linked libraries with full path: ./lib/libfat.a 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c -O2"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building tests/cw_test/cw_test.f90
Compiling tests/cw_test/cw_test.f90 serially
tests/cw_test/cw_test.f90:16:8:

     use pyplot_module
        1
Fatal Error: Can't open module file ‘pyplot_module.mod’ for reading at (1): No such file or directory
compilation terminated.

tests/cw_test/cw_test.f90:16:8:

     use pyplot_module
        1
Fatal Error: Can't open module file ‘pyplot_module.mod’ for reading at (1): No such file or directory
compilation terminated.
```

Let me know if it works for you.

**Comment by Juanlu001** [comment]
It works now @szaghi, grazie mille :) Closing!

**Comment by szaghi** [comment]
You are welcome.

Great Italian!
